/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "USART.h"
#include "MOTOR.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define F_CPU 1000000UL

void clock_init()
{
	//Enable port A clock
	RCC_GPIOA_CLK_EN();
	//Enable AFIO clock
	RCC_AFIO_CLK_EN();
}
void wait_ms(uint32_t time){
	uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}


int main(void)
{
	uint8_t data;
	clock_init();
	USART_CONFIG_t uartCFG;
	uartCFG.Baud_Rate = USART_BaudRate_9600;
	uartCFG.HW_FLW_CTRL = USART_HW_FLW_NONE;
	uartCFG.IRQ_Enable = USART_IRQ_NONE;
	uartCFG.Parity = USART_Parity_NONE;
	uartCFG.Word_Length = USART_WordLength_8BIT;
	uartCFG.Stop_Bits = USART_StopBits_1B;
	uartCFG.USART_Mode = USART_Mode_Transmitter_Receiver;
	MCAL_USART_Init(USART1, &uartCFG);
	MCAL_UART_GPIO_Set_Pins(USART1);
	HAL_MOTORS_Init();
	forword();
	while(1){
		MCAL_USART_Receive(USART1, &data, enable);
		switch(data){
				 case 'a':
					forword();
					wait_ms(4000);
					break;
				  case 'b':
					  BACK();
						wait_ms(4000);
					  break;
				   case 'c':
					 RIGHT();
						wait_ms(4000);
				          break;
				    case 'd':
					  LEFT();
						wait_ms(4000);
					  break;


				}
				/* stop actions*/
				wait_ms(5000);
				 STOP();


	}
}
