/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "USART.h"
#include "MOTOR.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define F_CPU 1000000UL
	uint8_t data;

void clock_init()
{
	//Enable port A clock
	RCC_GPIOA_CLK_EN();
	//Enable AFIO clock
	RCC_AFIO_CLK_EN();
}
void wait_ms(uint32_t time){
	uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}
void USART1_CallBack(void)
{

	switch(data){
			 case 'F':
				forword();
				break;
			  case 'B':
				  BACK();
				  break;
			   case 'R':
				 RIGHT();
			      break;
			    case 'L':
				  LEFT();
				  break;

			}

}

int main(void)
{
	clock_init();
	HAL_MOTORS_Init();


	USART_Config_t USART1_Config;

	USART1_Config.BaudRate = UART_BaudRate_9600;
	USART1_Config.HwFlowCtl = UART_HwFlowCtl_NONE;
	USART1_Config.IRQ_Enable = UART_IRQ_Enable_RXNEIE;
	USART1_Config.P_IRQ_CallBack = USART1_CallBack;
	USART1_Config.Parity = UART_Parity_NONE;
	USART1_Config.Payload_Length = UART_Payload_Length_8B;
	USART1_Config.StopBits = UART_StopBits_1;
	USART1_Config.USART_Mode = UART_Mode_TX_RX;
	MCAL_UART_Init(USART1, &USART1_Config);
	MCAL_UART_GPIO_Set_Pins(USART1);


	while(1){
		MCAL_UART_ReceiveData(USART1,& data, USART_disable);

	}
}
